__version__ = "0.0.0"

[__table__]
[[__table__.cmds]]
cmd = "virtualenv --python=python3 .env/"
code = "mkvenv"
desc = ""

[[__table__.cmds]]
cmd = "source .env/bin/activate.fish"
code = "actfish"
desc = ""

[[__table__.cmds]]
cmd = "pip install -r requirements.txt"
code = "pip"
desc = ""


